'''
GOAL: so here in the abbreviation MICE the word multivariate mean is that till now we are replacing or filling NAN values using a single variate either median, mean or mode etc.., but in MICE we will be using more than one variate to fill the missing NAN values. We will be doing this in the following steps:
        1. Firstly we will take the dataset, and plot only a selected count of values on the coordinate axis and shall draw a regression line.
        2.Now we will take the corresponding axis of missing value and shall find the missing value from the regression line Now we got our missing value, later again we would take another set of random values and draw another regression line this time we will get another value for the missing value.
       3.we shall repeat this further and at last we will get a set of multivariate possible values for the missing value.
      4. Now we will find the mean value in the column by replacing missing values with the values from the multivariate set, forming a set of mean values.
     5. finally we will take the mean of all possible means that are formed in above case, using this we get most unbiased value for our missing NAN value.

'''
from impyute.imputation.cs import mice
import pandas as pd
import numpy as np
import random
import sys
diab = np.genfromtxt('NaN_k-nn_filling.csv', delimiter=",")#taking the CSV dataset containing NaN values  and converting it into numpy.ndarray
# start the MICE training
imputed_training=mice(diab) #this mice function enables the happening of multivariate imputation by taking the mean of means generated by taking the missing value from the regression line
pd.DataFrame(imputed_training).to_csv("file_MICE.csv") # writing the replaced NAN values into a new csv file
